GET http://localhost:3000/api/places
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE3NDQxMjIyODQsImlhdCI6MTc0NDEyMTk4NH0.V6GqIExV0Kivo-GuBk80EMgj6yj6MSE35kg4YdsHkyw

###

POST http://localhost:3000/api/places
Content-Type: application/json

{
    "title": "Apartamento de prueba",
    "description": "Esto es para probar las inserciones",
    "address": "Calle Prueba 123",
    "size": 90,
    "postal_code": "29004",
    "price_per_month": 800
}
###

PUT  http://localhost:3000/api/places/21
Content-Type: application/json

{
    "title": "Apartamento de prueba",
    "description": "Esto es para probar las inserciones",
    "address": "Calle Prueba 123",
    "size": 120,
    "postal_code": "29001",
    "price_per_month": 1800
}

###

DELETE  http://localhost:3000/api/places/21

###

POST http://localhost:3000/api/users/register
Content-Type: application/json

{
    "username": "prueba2",
    "email": "prueba2@gmail.com",
    "password": "123456"
}

###

POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "prueba2@gmaIl.com",
    "password": "123456"
}

###